### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by CBID2** [3mdistal/portfolio#103]
Hi @3mdistal! I just read the announcement post on your blog. I the ideas you presented are wonderful,especially the categorization one. It’ll make it more personalized for readers. Another thing you should consider is adding a monetization widget, so you can get some sort of payment for your labor. Good luck! 😁

**Comment by 3mdistal** [comment]
Thanks so much, @CBID2 ! I'm really excited to keep up the work here.
