### ISSUE TITLE
Unexpected scrolling when navigating back to Studio page

### ISSUE THREAD

**Issue by codyjtclark** [3mdistal/portfolio#104]
The pages tmi, betson, and hfc scroll up and show half of the piano animation after clicking back, but jukebox, illustrations, and postcards pages do not.

An excessive large screencap: https://we.tl/t-vWDVk8kvey

**Comment by 3mdistal** [comment]
Though scroll behavior isn't what I'd like it to be, it is, for now, consistent. Will be fixing scroll behavior across the site sometime soon.
